### ISSUE TITLE
cd server && stack run gives error

### ISSUE THREAD

**Issue by tuuguu21** [therewillbecode/poker-maison#19]
**tuguldur@tuguldur-Inspiron-3537:~/Downloads/poker-maison-master/server$** stack run
poker-server-exe: Missing dbConnStr in env
CallStack (from HasCallStack):
  error, called at src/Env.hs:46:18 in poker-server-0.1.0.0-1noFjA1fxcLE6B4gEAhgPz:Env

**Comment by therewillbecode** [comment]
Look like you need to run the command with the correct env variable set with the database connection string for Postgres.

```dbConnStr='host=0.0.0.0 port=5432 user=tuguu21 dbname=pokerdb password=pass' stack run```

Of course make sure you create the database and update the string with the parameters.
